# Trivy Scanning YAML File
name: Trivy Scan

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run Trivy Scan
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: config
          exit-code: "1"
          severity: "HIGH,CRITICAL"
